// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    [UnityEngine.Scripting.Preserve]
    public class Binding_ebd8dda8688470340af97f69a9c4d9de_e763cd7f9efc4d058e0cd9635d2dbc40 : PositionBinding
    {   
        private global::UnityEngine.RectTransform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.RectTransform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_ebd8dda8688470340af97f69a9c4d9de : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_ebd8dda8688470340af97f69a9c4d9de>();
        
        private global::SendChat _ebd8dda8688470340af97f69a9c4d9de_c81e2014c5d24664992a72dc70220deb_CommandTarget;
        private global::SendChat _ebd8dda8688470340af97f69a9c4d9de_08ae9e1a8a6d4b5ab3a455fb480466b2_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["e763cd7f9efc4d058e0cd9635d2dbc40"] = new Binding_ebd8dda8688470340af97f69a9c4d9de_e763cd7f9efc4d058e0cd9635d2dbc40(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_ebd8dda8688470340af97f69a9c4d9de()
        {
            bakedCommandBindings.Add("c81e2014c5d24664992a72dc70220deb", BakeCommandBinding__ebd8dda8688470340af97f69a9c4d9de_c81e2014c5d24664992a72dc70220deb);
            bakedCommandBindings.Add("08ae9e1a8a6d4b5ab3a455fb480466b2", BakeCommandBinding__ebd8dda8688470340af97f69a9c4d9de_08ae9e1a8a6d4b5ab3a455fb480466b2);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        private void BakeCommandBinding__ebd8dda8688470340af97f69a9c4d9de_c81e2014c5d24664992a72dc70220deb(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _ebd8dda8688470340af97f69a9c4d9de_c81e2014c5d24664992a72dc70220deb_CommandTarget = (global::SendChat)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"SendChat.OnChatMessage",
            	"(System.String)",
            	SendCommand__ebd8dda8688470340af97f69a9c4d9de_c81e2014c5d24664992a72dc70220deb,
            	ReceiveLocalCommand__ebd8dda8688470340af97f69a9c4d9de_c81e2014c5d24664992a72dc70220deb,
            	MessageTarget.All,
            	_ebd8dda8688470340af97f69a9c4d9de_c81e2014c5d24664992a72dc70220deb_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__ebd8dda8688470340af97f69a9c4d9de_c81e2014c5d24664992a72dc70220deb(GenericCommandRequestArgs requestArgs)
        {
            var command = new _ebd8dda8688470340af97f69a9c4d9de_c81e2014c5d24664992a72dc70220deb();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.message = (System.String)requestArgs.Args[0];

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__ebd8dda8688470340af97f69a9c4d9de_c81e2014c5d24664992a72dc70220deb(GenericCommandRequestArgs requestArgs)
        {
            var command = new _ebd8dda8688470340af97f69a9c4d9de_c81e2014c5d24664992a72dc70220deb();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.message = (System.String)requestArgs.Args[0];

            ReceiveCommand__ebd8dda8688470340af97f69a9c4d9de_c81e2014c5d24664992a72dc70220deb(command);
        }

        private void ReceiveCommand__ebd8dda8688470340af97f69a9c4d9de_c81e2014c5d24664992a72dc70220deb(_ebd8dda8688470340af97f69a9c4d9de_c81e2014c5d24664992a72dc70220deb command)
        {
            var target = _ebd8dda8688470340af97f69a9c4d9de_c81e2014c5d24664992a72dc70220deb_CommandTarget;
			target.OnChatMessage((System.String)(command.message));
        }
        private void BakeCommandBinding__ebd8dda8688470340af97f69a9c4d9de_08ae9e1a8a6d4b5ab3a455fb480466b2(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _ebd8dda8688470340af97f69a9c4d9de_08ae9e1a8a6d4b5ab3a455fb480466b2_CommandTarget = (global::SendChat)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"SendChat.SendCommand",
            	"()",
            	SendCommand__ebd8dda8688470340af97f69a9c4d9de_08ae9e1a8a6d4b5ab3a455fb480466b2,
            	ReceiveLocalCommand__ebd8dda8688470340af97f69a9c4d9de_08ae9e1a8a6d4b5ab3a455fb480466b2,
            	MessageTarget.All,
            	_ebd8dda8688470340af97f69a9c4d9de_08ae9e1a8a6d4b5ab3a455fb480466b2_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__ebd8dda8688470340af97f69a9c4d9de_08ae9e1a8a6d4b5ab3a455fb480466b2(GenericCommandRequestArgs requestArgs)
        {
            var command = new _ebd8dda8688470340af97f69a9c4d9de_08ae9e1a8a6d4b5ab3a455fb480466b2();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;


            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__ebd8dda8688470340af97f69a9c4d9de_08ae9e1a8a6d4b5ab3a455fb480466b2(GenericCommandRequestArgs requestArgs)
        {
            var command = new _ebd8dda8688470340af97f69a9c4d9de_08ae9e1a8a6d4b5ab3a455fb480466b2();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;


            ReceiveCommand__ebd8dda8688470340af97f69a9c4d9de_08ae9e1a8a6d4b5ab3a455fb480466b2(command);
        }

        private void ReceiveCommand__ebd8dda8688470340af97f69a9c4d9de_08ae9e1a8a6d4b5ab3a455fb480466b2(_ebd8dda8688470340af97f69a9c4d9de_08ae9e1a8a6d4b5ab3a455fb480466b2 command)
        {
            var target = _ebd8dda8688470340af97f69a9c4d9de_08ae9e1a8a6d4b5ab3a455fb480466b2_CommandTarget;
			target.SendCommand();
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _ebd8dda8688470340af97f69a9c4d9de_c81e2014c5d24664992a72dc70220deb castedCommand:
                    ReceiveCommand__ebd8dda8688470340af97f69a9c4d9de_c81e2014c5d24664992a72dc70220deb(castedCommand);
                    break;
                case _ebd8dda8688470340af97f69a9c4d9de_08ae9e1a8a6d4b5ab3a455fb480466b2 castedCommand:
                    ReceiveCommand__ebd8dda8688470340af97f69a9c4d9de_08ae9e1a8a6d4b5ab3a455fb480466b2(castedCommand);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_ebd8dda8688470340af97f69a9c4d9de Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override void CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame, List<ICoherenceComponentData> components)
        {

            if (!usesLodsAtRuntime)
            {
                return;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                components.Add(new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                );

                return;                
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_ebd8dda8688470340af97f69a9c4d9de>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
