// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using Coherence.Toolkit;
    using Coherence.Toolkit.Bindings;
    using Coherence.Entities;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Toolkit.Bindings.ValueBindings;
    using Coherence.Toolkit.Bindings.TransformBindings;
    using Coherence.Connection;
    using Coherence.SimulationFrame;
    using Coherence.Interpolation;
    using Coherence.Log;
    using Logger = Coherence.Log.Logger;
    using UnityEngine.Scripting;
    [UnityEngine.Scripting.Preserve]
    public class Binding_a62034e61e33e3841abb0b8f8962eb9d_a21daece8bd544a3af4819694fca1ce0 : PositionBinding
    {   
        private global::UnityEngine.RectTransform CastedUnityComponent;

        protected override void OnBindingCloned()
        {
    	    CastedUnityComponent = (global::UnityEngine.RectTransform)UnityComponent;
        }

        public override global::System.Type CoherenceComponentType => typeof(WorldPosition);
        public override string CoherenceComponentName => "WorldPosition";
        public override uint FieldMask => 0b00000000000000000000000000000001;

        public override UnityEngine.Vector3 Value
        {
            get { return (UnityEngine.Vector3)(coherenceSync.coherencePosition); }
            set { coherenceSync.coherencePosition = (UnityEngine.Vector3)(value); }
        }

        protected override (UnityEngine.Vector3 value, AbsoluteSimulationFrame simFrame) ReadComponentData(ICoherenceComponentData coherenceComponent, Vector3 floatingOriginDelta)
        {
            var value = ((WorldPosition)coherenceComponent).value;
            if (!coherenceSync.HasParentWithCoherenceSync) { value += floatingOriginDelta; }

            var simFrame = ((WorldPosition)coherenceComponent).valueSimulationFrame;
            
            return (value, simFrame);
        }

        public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent, AbsoluteSimulationFrame simFrame)
        {
            var update = (WorldPosition)coherenceComponent;
            if (Interpolator.IsInterpolationNone)
            {
                update.value = Value;
            }
            else
            {
                update.value = GetInterpolatedAt(simFrame / InterpolationSettings.SimulationFramesPerSecond);
            }

            update.valueSimulationFrame = simFrame;
            
            return update;
        }

        public override ICoherenceComponentData CreateComponentData()
        {
            return new WorldPosition();
        }    
    }

    [UnityEngine.Scripting.Preserve]
    public class CoherenceSync_a62034e61e33e3841abb0b8f8962eb9d : CoherenceSyncBaked
    {
        private Entity entityId;
        private Logger logger = Coherence.Log.Log.GetLogger<CoherenceSync_a62034e61e33e3841abb0b8f8962eb9d>();
        
        private global::SendChat _a62034e61e33e3841abb0b8f8962eb9d_91bf60f4f7a0427490846f03cc50ba52_CommandTarget;
        
        
        private IClient client;
        private CoherenceBridge bridge;
        
        private readonly Dictionary<string, Binding> bakedValueBindings = new Dictionary<string, Binding>()
        {
			["a21daece8bd544a3af4819694fca1ce0"] = new Binding_a62034e61e33e3841abb0b8f8962eb9d_a21daece8bd544a3af4819694fca1ce0(),
        };
        
        private Dictionary<string, Action<CommandBinding, CommandsHandler>> bakedCommandBindings = new Dictionary<string, Action<CommandBinding, CommandsHandler>>();
        
        public CoherenceSync_a62034e61e33e3841abb0b8f8962eb9d()
        {
            bakedCommandBindings.Add("91bf60f4f7a0427490846f03cc50ba52", BakeCommandBinding__a62034e61e33e3841abb0b8f8962eb9d_91bf60f4f7a0427490846f03cc50ba52);
        }
        
        public override Binding BakeValueBinding(Binding valueBinding)
        {
            if (bakedValueBindings.TryGetValue(valueBinding.guid, out var bakedBinding))
            {
                valueBinding.CloneTo(bakedBinding);
                return bakedBinding;
            }
            
            return null;
        }
        
        public override void BakeCommandBinding(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            if (bakedCommandBindings.TryGetValue(commandBinding.guid, out var commandBindingBaker))
            {
                commandBindingBaker.Invoke(commandBinding, commandsHandler);
            }
        }
        private void BakeCommandBinding__a62034e61e33e3841abb0b8f8962eb9d_91bf60f4f7a0427490846f03cc50ba52(CommandBinding commandBinding, CommandsHandler commandsHandler)
        {
            _a62034e61e33e3841abb0b8f8962eb9d_91bf60f4f7a0427490846f03cc50ba52_CommandTarget = (global::SendChat)commandBinding.UnityComponent;
            commandsHandler.AddBakedCommand(
            	"SendChat.ReceiveMessege",
            	"(System.String)",
            	SendCommand__a62034e61e33e3841abb0b8f8962eb9d_91bf60f4f7a0427490846f03cc50ba52,
            	ReceiveLocalCommand__a62034e61e33e3841abb0b8f8962eb9d_91bf60f4f7a0427490846f03cc50ba52,
            	MessageTarget.All,
            	_a62034e61e33e3841abb0b8f8962eb9d_91bf60f4f7a0427490846f03cc50ba52_CommandTarget,
            	commandBinding.UsesMeta());
        }
        
        private void SendCommand__a62034e61e33e3841abb0b8f8962eb9d_91bf60f4f7a0427490846f03cc50ba52(GenericCommandRequestArgs requestArgs)
        {
            var command = new _a62034e61e33e3841abb0b8f8962eb9d_91bf60f4f7a0427490846f03cc50ba52();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;
            command.UsesMeta = requestArgs.UsesMeta;
            command.Target = requestArgs.Target;
            command.Entity = entityId;

            command.message = (System.String)requestArgs.Args[0];

            client.SendCommand(command, requestArgs.ChannelID);
        }
        
        private void ReceiveLocalCommand__a62034e61e33e3841abb0b8f8962eb9d_91bf60f4f7a0427490846f03cc50ba52(GenericCommandRequestArgs requestArgs)
        {
            var command = new _a62034e61e33e3841abb0b8f8962eb9d_91bf60f4f7a0427490846f03cc50ba52();
            command.Frame = requestArgs.Frame;
            command.SenderClientID = requestArgs.Sender;

            command.message = (System.String)requestArgs.Args[0];

            ReceiveCommand__a62034e61e33e3841abb0b8f8962eb9d_91bf60f4f7a0427490846f03cc50ba52(command);
        }

        private void ReceiveCommand__a62034e61e33e3841abb0b8f8962eb9d_91bf60f4f7a0427490846f03cc50ba52(_a62034e61e33e3841abb0b8f8962eb9d_91bf60f4f7a0427490846f03cc50ba52 command)
        {
            var target = _a62034e61e33e3841abb0b8f8962eb9d_91bf60f4f7a0427490846f03cc50ba52_CommandTarget;
			target.ReceiveMessege((System.String)(command.message));
        }
        
        public override void ReceiveCommand(IEntityCommand command)
        {
            switch (command)
            {
                case _a62034e61e33e3841abb0b8f8962eb9d_91bf60f4f7a0427490846f03cc50ba52 castedCommand:
                    ReceiveCommand__a62034e61e33e3841abb0b8f8962eb9d_91bf60f4f7a0427490846f03cc50ba52(castedCommand);
                    break;
                default:
                    logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncReceiveCommandUnhandled,
                        $"CoherenceSync_a62034e61e33e3841abb0b8f8962eb9d Unhandled command: {command.GetType()}.");
                    break;
            }
        }
        
        public override void CreateEntity(bool usesLodsAtRuntime, string archetypeName, AbsoluteSimulationFrame simFrame, List<ICoherenceComponentData> components)
        {

            if (!usesLodsAtRuntime)
            {
                return;
            }
            
            if (Archetypes.IndexForName.TryGetValue(archetypeName, out int archetypeIndex))
            {
                components.Add(new ArchetypeComponent
                    {
                        index = archetypeIndex,
                        indexSimulationFrame = simFrame,
                        FieldsMask = 0b1
                    }
                );

                return;                
            }
    
            logger.Warning(Coherence.Log.Warning.ToolkitBakedSyncCreateEntityMissingArchetype,
                $"Unable to find archetype {archetypeName} in dictionary. Please, bake manually (coherence > Bake)");
        }
        
        public override void Dispose()
        {
        }
        
        public override void Initialize(Entity entityId, CoherenceBridge bridge, IClient client, CoherenceInput input, Logger logger)
        {
            this.logger = logger.With<CoherenceSync_a62034e61e33e3841abb0b8f8962eb9d>();
            this.bridge = bridge;
            this.entityId = entityId;
            this.client = client;        
        }
    }
}
