// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using System.Collections.Generic;
    using Coherence.ProtocolDef;
    using Coherence.Brook;
    using Coherence.Connection;
    using Coherence.Entities;
    using Coherence.Serializer;
    using Coherence.Log;
    using Coherence.SimulationFrame;


    [UnityEngine.Scripting.Preserve]

    public class Definition : IDefinition
    {
        public const string schemaId = "6fa797835dc0cf6e79b21e2478641f56ec96b690";
        public const uint InternalWorldPosition = 0;
        public const uint InternalWorldOrientation = 1;
        public const uint InternalLocalUserComponent = 2;
        public const uint InternalWorldPositionQuery = 3;
        public const uint InternalArchetypeComponent = 4;
        public const uint InternalPersistence = 5;
        public const uint InternalConnectedEntity = 6;
        public const uint InternalUniqueID = 7;
        public const uint InternalConnection = 8;
        public const uint InternalConnectionScene = 9;
        public const uint InternalGlobal = 10;
        public const uint InternalGlobalQuery = 11;
        public const uint InternalTag = 12;
        public const uint InternalTagQuery = 13;
        public const uint InternalPreserveChildren = 14;
        public const uint InternalScene = 15;
        public const uint InternalAssetId = 16;
        public const uint InternalGenericScale = 17;
        public const uint Internal_27f1ac5097d4ee4409fbb87ad14f76c2_4939570989761225410 = 18;
        public const uint Internal_27f1ac5097d4ee4409fbb87ad14f76c2_6525610836190113121 = 19;
        public const uint Internal_6ba8b7030c4bf544396f864fc9dd99de_107609493621447933 = 20;
        public const uint Internal_a0e6252c4d09f4fb28257804194356b6_5156161361901559470 = 21;
        public const uint Internal_ba50eecfd968a47c38959f27b05771b6_5459872012036489579 = 22;
        public const uint InternalArchetype_27f1ac5097d4ee4409fbb87ad14f76c2_WorldPosition_LOD0 = 23;
        public const uint InternalArchetype_27f1ac5097d4ee4409fbb87ad14f76c2_WorldOrientation_LOD0 = 24;
        public const uint InternalArchetype_27f1ac5097d4ee4409fbb87ad14f76c2_GenericScale_LOD0 = 25;
        public const uint InternalArchetype_27f1ac5097d4ee4409fbb87ad14f76c2__27f1ac5097d4ee4409fbb87ad14f76c2_6525610836190113121_LOD0 = 26;
        public const uint InternalArchetype_27f1ac5097d4ee4409fbb87ad14f76c2__27f1ac5097d4ee4409fbb87ad14f76c2_4939570989761225410_LOD0 = 27;
        public const uint InternalArchetype_6ba8b7030c4bf544396f864fc9dd99de_WorldPosition_LOD0 = 28;
        public const uint InternalArchetype_6ba8b7030c4bf544396f864fc9dd99de_WorldOrientation_LOD0 = 29;
        public const uint InternalArchetype_6ba8b7030c4bf544396f864fc9dd99de__6ba8b7030c4bf544396f864fc9dd99de_107609493621447933_LOD0 = 30;
        public const uint InternalArchetype_a0e6252c4d09f4fb28257804194356b6_WorldPosition_LOD0 = 31;
        public const uint InternalArchetype_a0e6252c4d09f4fb28257804194356b6_WorldOrientation_LOD0 = 32;
        public const uint InternalArchetype_a0e6252c4d09f4fb28257804194356b6_GenericScale_LOD0 = 33;
        public const uint InternalArchetype_a0e6252c4d09f4fb28257804194356b6__a0e6252c4d09f4fb28257804194356b6_5156161361901559470_LOD0 = 34;
        public const uint InternalArchetype_ba50eecfd968a47c38959f27b05771b6_WorldPosition_LOD0 = 35;
        public const uint InternalArchetype_ba50eecfd968a47c38959f27b05771b6__ba50eecfd968a47c38959f27b05771b6_5459872012036489579_LOD0 = 36;
        public const uint InternalAuthorityRequest = 0;
        public const uint InternalAuthorityTransfer = 1;
        public const uint InternalQuerySynced = 2;
        public const uint InternalAdoptOrphan = 3;
        public const uint InternalPersistenceReady = 4;
        public const uint InternalSceneIndexChanged = 5;
        public const uint Internal_7c751ec26a8223d4789f4058354a755f_0cbf608705044c5ebf3b857a6e3d19f8 = 6;
        public const uint Internal_7c751ec26a8223d4789f4058354a755f_820c5828d87842c4a2e63920ffc0c16c = 7;
        public const uint Internal_a62034e61e33e3841abb0b8f8962eb9d_91bf60f4f7a0427490846f03cc50ba52 = 8;
        public const uint Internal_ca720d4ebce92554188a78a1512b88d3_27c99cf5ed374028996940463609a70e = 9;
        public const uint Internal_ca720d4ebce92554188a78a1512b88d3_e3ea5d70793143c0a65cb3054b3a0742 = 10;

        private static readonly Dictionary<uint, string> componentNamesForTypeIds = new Dictionary<uint, string>()
        {
            { 0, "WorldPosition" },
            { 1, "WorldOrientation" },
            { 2, "LocalUserComponent" },
            { 3, "WorldPositionQuery" },
            { 4, "ArchetypeComponent" },
            { 5, "Persistence" },
            { 6, "ConnectedEntity" },
            { 7, "UniqueID" },
            { 8, "Connection" },
            { 9, "ConnectionScene" },
            { 10, "Global" },
            { 11, "GlobalQuery" },
            { 12, "Tag" },
            { 13, "TagQuery" },
            { 14, "PreserveChildren" },
            { 15, "Scene" },
            { 16, "AssetId" },
            { 17, "GenericScale" },
            { 18, "_27f1ac5097d4ee4409fbb87ad14f76c2_4939570989761225410" },
            { 19, "_27f1ac5097d4ee4409fbb87ad14f76c2_6525610836190113121" },
            { 20, "_6ba8b7030c4bf544396f864fc9dd99de_107609493621447933" },
            { 21, "_a0e6252c4d09f4fb28257804194356b6_5156161361901559470" },
            { 22, "_ba50eecfd968a47c38959f27b05771b6_5459872012036489579" },
            { 23, "Archetype_27f1ac5097d4ee4409fbb87ad14f76c2_WorldPosition_LOD0" },
            { 24, "Archetype_27f1ac5097d4ee4409fbb87ad14f76c2_WorldOrientation_LOD0" },
            { 25, "Archetype_27f1ac5097d4ee4409fbb87ad14f76c2_GenericScale_LOD0" },
            { 26, "Archetype_27f1ac5097d4ee4409fbb87ad14f76c2__27f1ac5097d4ee4409fbb87ad14f76c2_6525610836190113121_LOD0" },
            { 27, "Archetype_27f1ac5097d4ee4409fbb87ad14f76c2__27f1ac5097d4ee4409fbb87ad14f76c2_4939570989761225410_LOD0" },
            { 28, "Archetype_6ba8b7030c4bf544396f864fc9dd99de_WorldPosition_LOD0" },
            { 29, "Archetype_6ba8b7030c4bf544396f864fc9dd99de_WorldOrientation_LOD0" },
            { 30, "Archetype_6ba8b7030c4bf544396f864fc9dd99de__6ba8b7030c4bf544396f864fc9dd99de_107609493621447933_LOD0" },
            { 31, "Archetype_a0e6252c4d09f4fb28257804194356b6_WorldPosition_LOD0" },
            { 32, "Archetype_a0e6252c4d09f4fb28257804194356b6_WorldOrientation_LOD0" },
            { 33, "Archetype_a0e6252c4d09f4fb28257804194356b6_GenericScale_LOD0" },
            { 34, "Archetype_a0e6252c4d09f4fb28257804194356b6__a0e6252c4d09f4fb28257804194356b6_5156161361901559470_LOD0" },
            { 35, "Archetype_ba50eecfd968a47c38959f27b05771b6_WorldPosition_LOD0" },
            { 36, "Archetype_ba50eecfd968a47c38959f27b05771b6__ba50eecfd968a47c38959f27b05771b6_5459872012036489579_LOD0" },
        };

        public static string ComponentNameForTypeId(uint typeId)
        {
            if (componentNamesForTypeIds.TryGetValue(typeId, out string componentName))
            {
                return componentName;
            }
            else
            {
                return "";
            }
        }

        public static readonly Dictionary<uint, MessageTarget> CommandRoutingByType = new Dictionary<uint, MessageTarget>()
        {
            { Definition.InternalAuthorityRequest , MessageTarget.All },
            { Definition.InternalAuthorityTransfer , MessageTarget.All },
            { Definition.InternalQuerySynced , MessageTarget.All },
            { Definition.InternalAdoptOrphan , MessageTarget.All },
            { Definition.InternalPersistenceReady , MessageTarget.All },
            { Definition.InternalSceneIndexChanged , MessageTarget.All },
            { Definition.Internal_7c751ec26a8223d4789f4058354a755f_0cbf608705044c5ebf3b857a6e3d19f8 , MessageTarget.All },
            { Definition.Internal_7c751ec26a8223d4789f4058354a755f_820c5828d87842c4a2e63920ffc0c16c , MessageTarget.All },
            { Definition.Internal_a62034e61e33e3841abb0b8f8962eb9d_91bf60f4f7a0427490846f03cc50ba52 , MessageTarget.All },
            { Definition.Internal_ca720d4ebce92554188a78a1512b88d3_27c99cf5ed374028996940463609a70e , MessageTarget.All },
            { Definition.Internal_ca720d4ebce92554188a78a1512b88d3_e3ea5d70793143c0a65cb3054b3a0742 , MessageTarget.All },
        };

        public ICoherenceComponentData ReadComponentUpdate(uint componentType, AbsoluteSimulationFrame referenceSimulationFrame,
            IInBitStream bitStream, Logger logger)
        {
            var inProtocolStream = new InProtocolBitStream(bitStream);

            switch (componentType)
            {
                case InternalWorldPosition:
                    return WorldPosition.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalWorldOrientation:
                    return WorldOrientation.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalLocalUserComponent:
                    return LocalUserComponent.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalWorldPositionQuery:
                    return WorldPositionQuery.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalArchetypeComponent:
                    return ArchetypeComponent.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalPersistence:
                    return Persistence.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalConnectedEntity:
                    return ConnectedEntity.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalUniqueID:
                    return UniqueID.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalConnection:
                    return Connection.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalConnectionScene:
                    return ConnectionScene.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalGlobal:
                    return Global.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalGlobalQuery:
                    return GlobalQuery.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalTag:
                    return Tag.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalTagQuery:
                    return TagQuery.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalPreserveChildren:
                    return PreserveChildren.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalScene:
                    return Scene.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalAssetId:
                    return AssetId.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalGenericScale:
                    return GenericScale.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_27f1ac5097d4ee4409fbb87ad14f76c2_4939570989761225410:
                    return _27f1ac5097d4ee4409fbb87ad14f76c2_4939570989761225410.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_27f1ac5097d4ee4409fbb87ad14f76c2_6525610836190113121:
                    return _27f1ac5097d4ee4409fbb87ad14f76c2_6525610836190113121.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_6ba8b7030c4bf544396f864fc9dd99de_107609493621447933:
                    return _6ba8b7030c4bf544396f864fc9dd99de_107609493621447933.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_a0e6252c4d09f4fb28257804194356b6_5156161361901559470:
                    return _a0e6252c4d09f4fb28257804194356b6_5156161361901559470.Deserialize(referenceSimulationFrame, inProtocolStream);
                case Internal_ba50eecfd968a47c38959f27b05771b6_5459872012036489579:
                    return _ba50eecfd968a47c38959f27b05771b6_5459872012036489579.Deserialize(referenceSimulationFrame, inProtocolStream);
                case InternalArchetype_27f1ac5097d4ee4409fbb87ad14f76c2_WorldPosition_LOD0:
                    return WorldPosition.DeserializeArchetype_27f1ac5097d4ee4409fbb87ad14f76c2_WorldPosition_LOD0(referenceSimulationFrame, inProtocolStream);
                case InternalArchetype_27f1ac5097d4ee4409fbb87ad14f76c2_WorldOrientation_LOD0:
                    return WorldOrientation.DeserializeArchetype_27f1ac5097d4ee4409fbb87ad14f76c2_WorldOrientation_LOD0(referenceSimulationFrame, inProtocolStream);
                case InternalArchetype_27f1ac5097d4ee4409fbb87ad14f76c2_GenericScale_LOD0:
                    return GenericScale.DeserializeArchetype_27f1ac5097d4ee4409fbb87ad14f76c2_GenericScale_LOD0(referenceSimulationFrame, inProtocolStream);
                case InternalArchetype_27f1ac5097d4ee4409fbb87ad14f76c2__27f1ac5097d4ee4409fbb87ad14f76c2_6525610836190113121_LOD0:
                    return _27f1ac5097d4ee4409fbb87ad14f76c2_6525610836190113121.DeserializeArchetype_27f1ac5097d4ee4409fbb87ad14f76c2__27f1ac5097d4ee4409fbb87ad14f76c2_6525610836190113121_LOD0(referenceSimulationFrame, inProtocolStream);
                case InternalArchetype_27f1ac5097d4ee4409fbb87ad14f76c2__27f1ac5097d4ee4409fbb87ad14f76c2_4939570989761225410_LOD0:
                    return _27f1ac5097d4ee4409fbb87ad14f76c2_4939570989761225410.DeserializeArchetype_27f1ac5097d4ee4409fbb87ad14f76c2__27f1ac5097d4ee4409fbb87ad14f76c2_4939570989761225410_LOD0(referenceSimulationFrame, inProtocolStream);
                case InternalArchetype_6ba8b7030c4bf544396f864fc9dd99de_WorldPosition_LOD0:
                    return WorldPosition.DeserializeArchetype_6ba8b7030c4bf544396f864fc9dd99de_WorldPosition_LOD0(referenceSimulationFrame, inProtocolStream);
                case InternalArchetype_6ba8b7030c4bf544396f864fc9dd99de_WorldOrientation_LOD0:
                    return WorldOrientation.DeserializeArchetype_6ba8b7030c4bf544396f864fc9dd99de_WorldOrientation_LOD0(referenceSimulationFrame, inProtocolStream);
                case InternalArchetype_6ba8b7030c4bf544396f864fc9dd99de__6ba8b7030c4bf544396f864fc9dd99de_107609493621447933_LOD0:
                    return _6ba8b7030c4bf544396f864fc9dd99de_107609493621447933.DeserializeArchetype_6ba8b7030c4bf544396f864fc9dd99de__6ba8b7030c4bf544396f864fc9dd99de_107609493621447933_LOD0(referenceSimulationFrame, inProtocolStream);
                case InternalArchetype_a0e6252c4d09f4fb28257804194356b6_WorldPosition_LOD0:
                    return WorldPosition.DeserializeArchetype_a0e6252c4d09f4fb28257804194356b6_WorldPosition_LOD0(referenceSimulationFrame, inProtocolStream);
                case InternalArchetype_a0e6252c4d09f4fb28257804194356b6_WorldOrientation_LOD0:
                    return WorldOrientation.DeserializeArchetype_a0e6252c4d09f4fb28257804194356b6_WorldOrientation_LOD0(referenceSimulationFrame, inProtocolStream);
                case InternalArchetype_a0e6252c4d09f4fb28257804194356b6_GenericScale_LOD0:
                    return GenericScale.DeserializeArchetype_a0e6252c4d09f4fb28257804194356b6_GenericScale_LOD0(referenceSimulationFrame, inProtocolStream);
                case InternalArchetype_a0e6252c4d09f4fb28257804194356b6__a0e6252c4d09f4fb28257804194356b6_5156161361901559470_LOD0:
                    return _a0e6252c4d09f4fb28257804194356b6_5156161361901559470.DeserializeArchetype_a0e6252c4d09f4fb28257804194356b6__a0e6252c4d09f4fb28257804194356b6_5156161361901559470_LOD0(referenceSimulationFrame, inProtocolStream);
                case InternalArchetype_ba50eecfd968a47c38959f27b05771b6_WorldPosition_LOD0:
                    return WorldPosition.DeserializeArchetype_ba50eecfd968a47c38959f27b05771b6_WorldPosition_LOD0(referenceSimulationFrame, inProtocolStream);
                case InternalArchetype_ba50eecfd968a47c38959f27b05771b6__ba50eecfd968a47c38959f27b05771b6_5459872012036489579_LOD0:
                    return _ba50eecfd968a47c38959f27b05771b6_5459872012036489579.DeserializeArchetype_ba50eecfd968a47c38959f27b05771b6__ba50eecfd968a47c38959f27b05771b6_5459872012036489579_LOD0(referenceSimulationFrame, inProtocolStream);
                default:
                    throw new System.ArgumentOutOfRangeException(nameof(componentType),
                        $"Missing serialization implementation for a component: {componentType}");
            }
        }

        public uint WriteComponentUpdate(ICoherenceComponentData data, uint serializeAs, bool isRefSimFrameValid,
            AbsoluteSimulationFrame referenceSimulationFrame, IOutProtocolBitStream protocolStream, Logger logger)
        {
            switch (serializeAs)
            {
                case InternalWorldPosition:
                    return WorldPosition.Serialize((WorldPosition)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalWorldOrientation:
                    return WorldOrientation.Serialize((WorldOrientation)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalLocalUserComponent:
                    return LocalUserComponent.Serialize((LocalUserComponent)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalWorldPositionQuery:
                    return WorldPositionQuery.Serialize((WorldPositionQuery)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalArchetypeComponent:
                    return ArchetypeComponent.Serialize((ArchetypeComponent)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalPersistence:
                    return Persistence.Serialize((Persistence)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalConnectedEntity:
                    return ConnectedEntity.Serialize((ConnectedEntity)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalUniqueID:
                    return UniqueID.Serialize((UniqueID)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalConnection:
                    return Connection.Serialize((Connection)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalConnectionScene:
                    return ConnectionScene.Serialize((ConnectionScene)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalGlobal:
                    return Global.Serialize((Global)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalGlobalQuery:
                    return GlobalQuery.Serialize((GlobalQuery)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalTag:
                    return Tag.Serialize((Tag)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalTagQuery:
                    return TagQuery.Serialize((TagQuery)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalPreserveChildren:
                    return PreserveChildren.Serialize((PreserveChildren)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalScene:
                    return Scene.Serialize((Scene)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalAssetId:
                    return AssetId.Serialize((AssetId)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case InternalGenericScale:
                    return GenericScale.Serialize((GenericScale)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_27f1ac5097d4ee4409fbb87ad14f76c2_4939570989761225410:
                    return _27f1ac5097d4ee4409fbb87ad14f76c2_4939570989761225410.Serialize((_27f1ac5097d4ee4409fbb87ad14f76c2_4939570989761225410)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_27f1ac5097d4ee4409fbb87ad14f76c2_6525610836190113121:
                    return _27f1ac5097d4ee4409fbb87ad14f76c2_6525610836190113121.Serialize((_27f1ac5097d4ee4409fbb87ad14f76c2_6525610836190113121)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_6ba8b7030c4bf544396f864fc9dd99de_107609493621447933:
                    return _6ba8b7030c4bf544396f864fc9dd99de_107609493621447933.Serialize((_6ba8b7030c4bf544396f864fc9dd99de_107609493621447933)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_a0e6252c4d09f4fb28257804194356b6_5156161361901559470:
                    return _a0e6252c4d09f4fb28257804194356b6_5156161361901559470.Serialize((_a0e6252c4d09f4fb28257804194356b6_5156161361901559470)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                case Internal_ba50eecfd968a47c38959f27b05771b6_5459872012036489579:
                    return _ba50eecfd968a47c38959f27b05771b6_5459872012036489579.Serialize((_ba50eecfd968a47c38959f27b05771b6_5459872012036489579)data, isRefSimFrameValid, referenceSimulationFrame, protocolStream, logger);
                default:
                    logger.Error(Coherence.Log.Error.DefinitionMissingComponentImplementation, ("component", data.GetComponentType()));
                    return 0;
            }
        }

        private IEntityCommand ReadCommand(uint commandType, Entity entity, MessageTarget target, IInProtocolBitStream bitStream, Logger logger)
        {
            switch (commandType)
            {
                case Definition.InternalAuthorityRequest:
                    return AuthorityRequest.Deserialize(bitStream, entity, target);
                case Definition.InternalAuthorityTransfer:
                    return AuthorityTransfer.Deserialize(bitStream, entity, target);
                case Definition.InternalQuerySynced:
                    return QuerySynced.Deserialize(bitStream, entity, target);
                case Definition.InternalAdoptOrphan:
                    return AdoptOrphan.Deserialize(bitStream, entity, target);
                case Definition.InternalPersistenceReady:
                    return PersistenceReady.Deserialize(bitStream, entity, target);
                case Definition.InternalSceneIndexChanged:
                    return SceneIndexChanged.Deserialize(bitStream, entity, target);
                case Definition.Internal_7c751ec26a8223d4789f4058354a755f_0cbf608705044c5ebf3b857a6e3d19f8:
                    return _7c751ec26a8223d4789f4058354a755f_0cbf608705044c5ebf3b857a6e3d19f8.Deserialize(bitStream, entity, target);
                case Definition.Internal_7c751ec26a8223d4789f4058354a755f_820c5828d87842c4a2e63920ffc0c16c:
                    return _7c751ec26a8223d4789f4058354a755f_820c5828d87842c4a2e63920ffc0c16c.Deserialize(bitStream, entity, target);
                case Definition.Internal_a62034e61e33e3841abb0b8f8962eb9d_91bf60f4f7a0427490846f03cc50ba52:
                    return _a62034e61e33e3841abb0b8f8962eb9d_91bf60f4f7a0427490846f03cc50ba52.Deserialize(bitStream, entity, target);
                case Definition.Internal_ca720d4ebce92554188a78a1512b88d3_27c99cf5ed374028996940463609a70e:
                    return _ca720d4ebce92554188a78a1512b88d3_27c99cf5ed374028996940463609a70e.Deserialize(bitStream, entity, target);
                case Definition.Internal_ca720d4ebce92554188a78a1512b88d3_e3ea5d70793143c0a65cb3054b3a0742:
                    return _ca720d4ebce92554188a78a1512b88d3_e3ea5d70793143c0a65cb3054b3a0742.Deserialize(bitStream, entity, target);
                default:
                    throw new System.ArgumentOutOfRangeException(nameof(commandType),
                        $"Missing serialization implementation for a command: {commandType}");
            }
        }

        private IEntityInput ReadInput(uint inputType, Entity entity, long frame, IInProtocolBitStream bitStream, Logger logger)
        {
            switch (inputType)
            {
                default:
                    throw new System.ArgumentOutOfRangeException(nameof(inputType),
                        $"Missing serialization implementation for an input: {inputType}");
            }
        }

        public IEntityCommand[]	ReadCommands(IInBitStream bitStream, Logger logger)
        {
            var numMessages = bitStream.ReadUint8();

            var commandData = new IEntityCommand[numMessages];

            for (var i = 0; i < numMessages; i++)
            {
            	commandData[i] = ReadCommand(bitStream, logger);
            }

            return commandData;
        }

        public IEntityInput[] ReadInputs(IInBitStream bitStream, Logger logger)
        {
            var numMessages = bitStream.ReadUint8();

            var inputData = new IEntityInput[numMessages];

            for (var i = 0; i < numMessages; i++)
            {
                var entityID = DeserializerTools.DeserializeEntity(bitStream);
                var routing = DeserializerTools.DeserializeMessageTarget(bitStream);
                var componentType = DeserializerTools.DeserializeComponentTypeID(bitStream);
                var inBitStream = new Coherence.Serializer.InProtocolBitStream(bitStream);
                var frame = (long)bitStream.ReadUint64();
                var input = ReadInput(componentType, entityID, frame, inBitStream, logger);
                input.Routing = routing;
                inputData[i] = input;
            }

            return inputData;
        }

        public IEntityCommand ReadCommand(IInBitStream bitStream, Logger logger)
        {
            var entityID = DeserializerTools.DeserializeEntity(bitStream);
            var messageTarget = DeserializerTools.DeserializeMessageTarget(bitStream);
            var componentType = DeserializerTools.DeserializeComponentTypeID(bitStream);
            var meta = DeserializerTools.DeserializeCommandMeta(bitStream);
            var inBitStream = new Coherence.Serializer.InProtocolBitStream(bitStream);

			var command = ReadCommand(componentType, entityID, messageTarget, inBitStream, logger);
			if (meta.HasValue)
			{
				command.UsesMeta = true;
				command.SenderClientID = new ClientID(meta.Value.SenderID);
				command.Frame = meta.Value.Frame;
			}

            return command;
        }

        public void WriteCommand(IEntityCommand data, uint commandType, IOutProtocolBitStream bitStream, Logger logger)
        {
            switch (commandType)
            {
                case Definition.InternalAuthorityRequest:
                    AuthorityRequest.Serialize((AuthorityRequest)data, bitStream);
                    break;
                case Definition.InternalAuthorityTransfer:
                    AuthorityTransfer.Serialize((AuthorityTransfer)data, bitStream);
                    break;
                case Definition.InternalQuerySynced:
                    QuerySynced.Serialize((QuerySynced)data, bitStream);
                    break;
                case Definition.InternalAdoptOrphan:
                    AdoptOrphan.Serialize((AdoptOrphan)data, bitStream);
                    break;
                case Definition.InternalPersistenceReady:
                    PersistenceReady.Serialize((PersistenceReady)data, bitStream);
                    break;
                case Definition.InternalSceneIndexChanged:
                    SceneIndexChanged.Serialize((SceneIndexChanged)data, bitStream);
                    break;
                case Definition.Internal_7c751ec26a8223d4789f4058354a755f_0cbf608705044c5ebf3b857a6e3d19f8:
                    _7c751ec26a8223d4789f4058354a755f_0cbf608705044c5ebf3b857a6e3d19f8.Serialize((_7c751ec26a8223d4789f4058354a755f_0cbf608705044c5ebf3b857a6e3d19f8)data, bitStream);
                    break;
                case Definition.Internal_7c751ec26a8223d4789f4058354a755f_820c5828d87842c4a2e63920ffc0c16c:
                    _7c751ec26a8223d4789f4058354a755f_820c5828d87842c4a2e63920ffc0c16c.Serialize((_7c751ec26a8223d4789f4058354a755f_820c5828d87842c4a2e63920ffc0c16c)data, bitStream);
                    break;
                case Definition.Internal_a62034e61e33e3841abb0b8f8962eb9d_91bf60f4f7a0427490846f03cc50ba52:
                    _a62034e61e33e3841abb0b8f8962eb9d_91bf60f4f7a0427490846f03cc50ba52.Serialize((_a62034e61e33e3841abb0b8f8962eb9d_91bf60f4f7a0427490846f03cc50ba52)data, bitStream);
                    break;
                case Definition.Internal_ca720d4ebce92554188a78a1512b88d3_27c99cf5ed374028996940463609a70e:
                    _ca720d4ebce92554188a78a1512b88d3_27c99cf5ed374028996940463609a70e.Serialize((_ca720d4ebce92554188a78a1512b88d3_27c99cf5ed374028996940463609a70e)data, bitStream);
                    break;
                case Definition.Internal_ca720d4ebce92554188a78a1512b88d3_e3ea5d70793143c0a65cb3054b3a0742:
                    _ca720d4ebce92554188a78a1512b88d3_e3ea5d70793143c0a65cb3054b3a0742.Serialize((_ca720d4ebce92554188a78a1512b88d3_e3ea5d70793143c0a65cb3054b3a0742)data, bitStream);
                    break;
                default:
                    logger.Error(Coherence.Log.Error.DefinitionMissingCommandImplementation, ("command", commandType));
                    break;
            }
        }

        public void WriteInput(IEntityInput data, uint inputType, IOutProtocolBitStream bitStream, Logger logger)
        {
            var inputData = (InputData)data;

            switch (inputType)
            {
                default:
                    logger.Error(Coherence.Log.Error.DefinitionMissingInputImplementation, ("input", inputType));
                    break;
            }
        }

        public IEntityCommand CreateAuthorityRequest(Entity entity, ClientID requester, AuthorityType authType)
        {
            return new AuthorityRequest(entity, (uint)requester, (int)authType)
			{
				Target = MessageTarget.StateAuthorityOnly,
			};
        }

        public IEntityCommand CreateAdoptOrphanCommand(Entity entity)
        {
            return new AdoptOrphan
            {
                Entity = entity,
                Target = MessageTarget.StateAuthorityOnly,
            };
        }

        public bool TryGetAuthorityRequestCommand(IEntityCommand entityCommand,
            out ClientID requester, out AuthorityType authType)
        {
            if (entityCommand is AuthorityRequest request)
            {
                requester = (ClientID)request.requester;
                authType = (AuthorityType)request.authorityType;

                return true;
            }

            requester = default;
            authType = default;

            return false;
        }

        public IEntityCommand CreateAuthorityTransfer(Entity entity, ClientID newAuthority, bool accepted, AuthorityType authType)
        {
            return new AuthorityTransfer(entity, (uint)newAuthority, accepted, (int)authType)
			{
				Target = MessageTarget.Other,
			};
        }

        public bool TryGetAuthorityTransferCommand(IEntityCommand entityCommand, out ClientID newAuthority,
            out bool transferAccepted, out AuthorityType authType)
        {
            if (entityCommand is AuthorityTransfer transfer)
            {
                newAuthority = (ClientID)transfer.newAuthority;
                transferAccepted = transfer.accepted;
                authType = (AuthorityType)transfer.authorityType;

                return true;
            }

            newAuthority = default;
            transferAccepted = default;
            authType = default;

            return false;
        }

        public ICoherenceComponentData GeneratePersistenceData()
        {
            var persistence = new Persistence();

            return persistence;
        }

        public ICoherenceComponentData GenerateCoherenceUUIDData(string uuid, AbsoluteSimulationFrame simFrame)
        {
            var uniqueID = new UniqueID();
            uniqueID.uuid = uuid;
            uniqueID.uuidSimulationFrame = simFrame;
            uniqueID.FieldsMask = 0b1;

            return uniqueID;
        }

        public ICoherenceComponentData CreateGlobalComponent()
        {
            return new Global();
        }

        public ICoherenceComponentData GenerateGlobalQueryComponent()
        {
            return new GlobalQuery();
        }

        public string ExtractCoherenceUUID(ICoherenceComponentData data)
        {
            var uniqueID = (UniqueID)data;
            return uniqueID.uuid;
        }

        public bool IsConnectedEntity(ICoherenceComponentData data)
        {
            return data.GetComponentType() == Definition.InternalConnectedEntity;
        }

        public Entity ExtractConnectedEntityID(ICoherenceComponentData data)
        {
            var connectedEntity = (ConnectedEntity)data;

            return connectedEntity.value;
        }

        public string ExtractCoherenceTag(ICoherenceComponentData data)
        {
            var tag = (Tag)data;
            return tag.tag;
        }

        public bool TryGetSceneIndexChangedCommand(IEntityCommand entityCommand, out int sceneIndex)
        {
            if (entityCommand is SceneIndexChanged changed)
            {
                sceneIndex = (int)changed.sceneIndex;

                return true;
            }

            sceneIndex = default;

            return false;
        }

        public IEntityCommand CreateSceneIndexChangedCommand(Entity entity, int sceneIndex)
        {
            return new SceneIndexChanged(entity, sceneIndex)
			{
				Target = MessageTarget.StateAuthorityOnly,
			};
        }

        public bool IsSendOrderedComponent(uint componentID)
        {
            switch(componentID)
            {
                case 6:
                    return true;
                default:
                    return false;
            }
        }
}


}
